#! /bin/bash
# I'm WAS still using Gtk2!
# g++ -g `pkg-config --cflags gtk+-3.0 gdk-3.0 gdk-pixbuf-xlib-2.0` -o rbfilter ./rbfilter.cpp ./Calcs.cpp ./Rauch.cpp ./Sallen_and_Key.cpp ./Discrete.cpp `pkg-config --libs gtk+-3.0 gdk-3.0 gdk-pixbuf-xlib-3.0`
g++ -g `pkg-config --cflags gtk+-3.0 gdk-3.0` -o rbfilter ./rbfilter.cpp ./Calcs.cpp ./Rauch.cpp ./Sallen_and_Key.cpp ./Discrete.cpp `pkg-config --libs gtk+-3.0 gdk-3.0 gdk-pixbuf-xlib-2.0`
echo "Done!"
read

